[package]
name = "kicad-component-importer"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.217", features = ["derive"] }
tempfile = "3.10.1"
toml = "0.8.19"
walkdir = "2.5.0"
zip = "0.6.6"

[dev-dependencies]
